services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsTrinityDataBundle\Normalizer\DefaultResourceNormalizer:
        tags:
            - { name: dynamic_search.resource_normalizer, identifier: trinity_default_resource_normalizer, data_provider: trinity_data }

    DsTrinityDataBundle\Normalizer\LocalizedResourceNormalizer:
        tags:
            - { name: dynamic_search.resource_normalizer, identifier: trinity_localized_resource_normalizer, data_provider: trinity_data }